### ISSUE TITLE
UPnP - WAV file not playing

### ISSUE THREAD

**Issue by thomas0369** [LMS-Community/slimserver#1393]
**UPnP - WAV file not playing**
As soon as I try to play a WAV file via UPnP, an error is occurring with USB Audio Player Pro. I also tested BubbleUPnP.

**Docker Setup in Qnap**
```
version: '3.9'
services:
  lms:
    container_name: lms
    image: lmscommunity/lyrionmusicserver:stable
    volumes:
            - /share/Container/app-data/lms-config/:/config:rw
            - /share/AudioCDs/:/music:ro
            - /share/AudioCDs/Playlists/:/playlist:rw
    ports:
      - 9000:9000/tcp
      - 9090:9090/tcp
      - 3483:3483/tcp
      - 3483:3483/udp
    environment:
      - HTTP_PORT=9000
    restart: always
```

**Transcoding Log**
```
[25-05-14 21:43:40.7366] Slim::Player::TranscodingHelper::checkBin (269) Checking formats for: wav-pcm-*-*
[25-05-14 21:43:40.7367] Slim::Player::TranscodingHelper::enabledFormat (236) Checking to see if wav-pcm-*-* is enabled
[25-05-14 21:43:40.7368] Slim::Player::TranscodingHelper::checkBin (277)    enabled
[25-05-14 21:43:40.7369] Slim::Player::TranscodingHelper::checkBin (279)   Found command: -
[25-05-14 21:43:40.7371] Slim::Player::TranscodingHelper::getConvertCommand2 (494) Matched: wav->pcm via: -
[25-05-14 21:43:40.7374] Slim::Player::TranscodingHelper::tokenizeConvertCommand2 (668) Using command for conversion: - & |
```

USB Audio Player Pro shows "Failed to read track" as error message
BubbleUPnP shows nothing and don't play the song

When I play wav with Material-Skin its working fine:
**Transcoding Log with material skin**
```
[25-05-14 21:37:39.8187] Slim::Player::Song::open (424) Transcoder: streamMode=I, streamformat=pcm
[25-05-14 21:37:39.8188] Slim::Player::Song::open (479) Opening stream (no direct streaming) using Slim::Player::Protocols::File [file:///music/ABBA/1992-Gold_Greatest_Hits/01-Dancing_Queen.wav]
[25-05-14 21:37:39.8191] Slim::Player::Protocols::File::open (81) duration: [232.2] size: [40960088] endian [] offset: [1280] for file:///music/ABBA/1992-Gold_Greatest_Hits/01-Dancing_Queen.wav
[25-05-14 21:37:39.8191] Slim::Player::Protocols::File::open (98) Opening file /music/ABBA/1992-Gold_Greatest_Hits/01-Dancing_Queen.wav
[25-05-14 21:37:39.8193] Slim::Player::Protocols::File::open (190) Seeking in 1280 into /music/ABBA/1992-Gold_Greatest_Hits/01-Dancing_Queen.wav
[25-05-14 21:37:39.8195] Slim::Player::Song::open (509) URL is a song (audio): file:///music/ABBA/1992-Gold_Greatest_Hits/01-Dancing_Queen.wav, type=wav
[25-05-14 21:37:39.8232] Slim::Player::SongStreamController::new (37) live=1
[25-05-14 21:37:39.8237] Slim::Player::StreamingController::_Stream (1297) 9d:1a:f2:48:83:e3: stream
[25-05-14 21:37:39.8242] Slim::Player::StreamingController::_Stream (1334) Song queue is now 0
[25-05-14 21:37:39.8244] Slim::Player::StreamingController::_setPlayingState (2415) new playing state BUFFERING
[25-05-14 21:37:39.8245] Slim::Player::StreamingController::_setStreamingState (2424) new streaming state STREAMING
[25-05-14 21:37:39.8246] Slim::Player::StreamingController::_eventAction (301) 9d:1a:f2:48:83:e3: NextTrackReady - new state BUFFERING-STREAMING
[25-05-14 21:37:39.8247] Slim::Player::StreamingController::_eventAction (301) 9d:1a:f2:48:83:e3: Play - new state BUFFERING-STREAMING
[25-05-14 21:37:39.8508] Slim::Player::TranscodingHelper::checkBin (269) Checking formats for: wav-pcm-*-*
[25-05-14 21:37:39.8509] Slim::Player::TranscodingHelper::enabledFormat (236) Checking to see if wav-pcm-*-* is enabled
[25-05-14 21:37:39.8510] Slim::Player::TranscodingHelper::checkBin (277)    enabled
[25-05-14 21:37:39.8511] Slim::Player::TranscodingHelper::checkBin (279)   Found command: -
[25-05-14 21:37:39.8513] Slim::Player::TranscodingHelper::getConvertCommand2 (494) Matched: wav->pcm via: -
```

Do you have an idea why UPnP is not playing?
Thanks in advance!
